import "./globals.css";
import type { Metadata } from "next";
// Theme Registry component is used because createTheme from MUI can only be used in client components
import ThemeRegistry from "./theme-registry";
import Navbar from "@/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry options={{ key: "mui" }}>
        <body>
          <Navbar />
          {children}
        </body>
      </ThemeRegistry>
    </html>
  );
}
